rrtools::use_compendium("../datatoolboxexos/", open = FALSE)
usethis::use_r("data_wildfinder.R")
usethis::use_package(c("here", "readr"))
usethis::use_package("here")
usethis::use_package("readr")
rrtools::use_readme_rmd()
utils::sessionInfo()
devtools::install_deps()
devtools::document()
devtools::document()
load_all()
devtools::load_all()
devtools::document()
rm(list = c("data_ecoregion"))
rm(list = c("data_mammals"))
rm(list = c("data_mammals_ecoregions"))
devtools::install_deps()
devtools::load_all()
devtools::document()
library(datatoolboxexos)
devtools::check()
devtools::check()
devtools::load_all()