---
title: Rpackage for the automatic estimation of the parameters of the Von Bertalanffy fish growth model

author:
  - name:  Marine Ballutaud
    email: marine.ballutaud@univ-lille.fr
    affiliation: Université de Lille
    footnote: 1
  - name: Lyndsay Clavareau
    email: lyndsay.clavareau@ifremer.fr
    affiliation: IFREMER
    footnote: 2
  - name: Etienne Rouby
    email: etienne.rouby@univ-lr.fr
    affiliation: Observatoire Pelagis
    footnote: 2
  - name: Julien Renoult
    email: julien.renoult@blabla.com
    affiliation: Centre d’Ecologie Fonctionnelle et Evolutive
    footnote: 2
  - name: Fabienne Ribeyre
    email: fabienne.ribeyre@cirad.fr
    affiliation: Cirad
    footnote: 2
address:
  - code: Université de Lille
    address: Department, Street, City, State, Zip
footnote:
  - code: 1
    text: "Corresponding Author"
  - code: 2
    text: "Equal contribution"
abstract: |
  This is the abstract.

  

journal: "An awesome journal"
date: "`r Sys.Date()`"
bibliography: mybibfile.bib
#linenumbers: true
#numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
---


Introduction
============

This package was created as part of the training course "Good practices for reproducible research in digital ecology" co-organized by the Cesab of the FRB and the GDR EcoStat.
It uses the model de @Bertalanffy1938.



Material and methods
============

#### Datasource

The data used comes from the website https://www.fishbase.in/home.htm.

#### Statistical methods

The Growth model of Von Bertalanffy is $$Linf.(1-exp^{-K*(a-to)})$$
with Linf = maximum size, a = fish age, K and t0 are fixed parameters.

Model was adjusted using the method described by  @rafail_simple_1973.



Results
=======

The results of the model are presented in Figure 1.

```{r , eval = TRUE, echo=FALSE, fig.cap= "Growth curve obtained with the Growth model of Von Bertalanffy"}
data <- dataextract(espece)
fishplot(data)

```


Discussion
==========

Working with others on a project is much more complicated than working alone, but much faster.

Acknowledgement
==========
Merci à vous c'était un super projet !

References {#references .unnumbered}
==========

